In [3]:
from scipy.integrate import quad
def integrateFunction(x):
    return x

quad(integrateFunction,0,1)

def integrateFn(x,a,b):
    return a*x+b

a=3
b=2

quad(integrateFn,0,1, args=(a,b))

(3.5, 3.885780586188048e-14)

In [7]:
import numpy as np
from scipy import linalg
matrix=np.array([[23,4],[3,2]])
matrix

array([[23,  4],
       [ 3,  2]])

In [10]:
linalg.inv(matrix)

array([[ 0.05882353, -0.11764706],
       [-0.08823529,  0.67647059]])

In [12]:
linalg.det(matrix)

34.0

In [14]:
matrix*linalg.inv(matrix)

array([[ 1.35294118, -0.47058824],
       [-0.26470588,  1.35294118]])

In [16]:
import numpy as np
from scipy import linalg
test1 = np.array([[2,3],[4,5]])
eigenvalue,eigenvector = linalg.eig(test1)
first_eigen_value,second_eigen_value=eigenvalue
first_eigen_value,second_eigen_value

((-0.2749172176353749+0j), (7.274917217635375+0j))

In [17]:
eigenvector[:,0]

array([-0.79681209,  0.60422718])

In [29]:
#finding the linear system 

#2x + 3y + z  =21
#-x + 5y + 4z = 9
#3x + 2y + 9z = 6
#Above are the given values
#now find the Linear equn

import numpy as np
from scipy import linalg

eqn = np.array([[2,3,1],[-1,5,4],[3,2,9]])
total_given = np.array([21,9,6])

linalg.solve(eqn,total_given)



array([ 4.95,  4.35, -1.95])

In [31]:
eqn1 = np.array([[1,1],[4,9]])
total_given1 = np.array([30,150])
linalg.solve(eqn1,total_given1)

array([24.,  6.])

In [21]:
numSvd=np.array([[2,3,1],[3,2,4]])
linalg.svd(numSvd)

(array([[-0.53645416, -0.84392946],
        [-0.84392946,  0.53645416]]),
 array([6.25864179, 1.95688603]),
 array([[-0.57595511, -0.52682699, -0.62508323],
        [-0.04011294, -0.74551101,  0.66528512],
        [-0.81649658,  0.40824829,  0.40824829]]))

In [24]:
from scipy.stats import norm
norm.rvs(loc=0,scale=1,size=10)

array([-0.29422164, -0.86597686, -0.99148339,  2.18700585,  0.26373896,
        0.23550906,  0.99704812,  1.08827287, -0.39545808, -1.21636146])

In [27]:
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [32]:
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18

In [33]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
boston_dataset = load_boston()

In [35]:
boston_dataset['DESCR']

"Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n

In [36]:
#print the features of the dataset
boston_dataset['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [45]:
df_boston=pd.DataFrame(boston_dataset.data)
df_boston.columns=boston_dataset.feature_names
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [47]:
boston_dataset.data.shape

(506, 13)

In [49]:
boston_dataset.target.shape

(506,)

In [51]:
boston_dataset['target']

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [52]:
#Now how to create and train a linear Regression model
from sklearn.datasets import load_boston
boston_dataset = load_boston()

C:\Users\banan\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """


In [53]:
df_boston = pd.DataFrame(boston_dataset.data)
df_boston.column=boston_dataset.feature_names
df_boston['price']=boston_dataset.target

df_boston.head()

C:\Users\banan\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  


0     1     2    3      4      5     6       7    8      9    10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12  price  
0  396.90  4.98   24.0  
1  396.90  9.14   21.6  
2  392.83  4.03   34.7  
3  394.63  2.94   33.4  
4  396.90  5.33   36.2

In [65]:
#assign features on X-axis
X_features=boston_dataset.data

In [68]:
#assign features on Y-axis
Y_target=boston_dataset.target

In [70]:
from sklearn.linear_model import LinearRegression
lineReg = LinearRegression()
lineReg.fit(X_features,Y_target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [73]:
'the estimated intercept %.2f'%lineReg.intercept_

'the estimated intercept 36.49'

In [77]:
'the estimated Coeffient %d ' % len(lineReg.coef_)

'the estimated Coeffient 13 '

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_features,Y_target)
boston_dataset.data.shape

(506, 13)

In [84]:
X_train.shape,X_test.shape, Y_train.shape,Y_test.shape

((379, 13), (127, 13), (379,), (127,))

In [79]:
lineReg.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [81]:
'MSE value is %.2f' %np.mean((lineReg.predict(X_test)-Y_test)**2)

'MSE value is 21.97'

In [82]:
'Variance score is %.2f' % lineReg.score(X_test,Y_test)

'Variance score is 0.74'