In [4]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
iris_dataset=load_iris()
type(iris_dataset)
iris_dataset.DESCR

'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ============

In [5]:
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris_dataset.data.shape

(150, 4)

In [7]:
X_feature=iris_dataset.data
Y_target=iris_dataset.target
X_feature.shape

(150, 4)

In [8]:
Y_target.shape

(150,)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn
knn.fit(X_feature,Y_target)
X_new=[[3,4,3,2],[5,3,2,2]]
knn.predict(X_new)

array([1, 1])

In [11]:
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression()
logReg.fit(X_feature,Y_target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
logReg.predict(X_new)

array([2, 0])

In [13]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
n_samples = 300
random_state=20
X,y=make_blobs(n_samples,n_features=5,random_state=None)
predict_y=KMeans(n_clusters=3,random_state=random_state).fit_predict(X)
predict_y

array([1, 2, 2, 1, 2, 2, 0, 2, 0, 1, 1, 1, 0, 2, 1, 0, 2, 1, 1, 1, 1, 2,
       1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 0, 2, 0, 1, 1, 0,
       0, 1, 1, 2, 0, 2, 1, 0, 1, 0, 2, 2, 0, 2, 1, 2, 0, 0, 2, 1, 1, 2,
       2, 0, 1, 1, 0, 0, 1, 1, 0, 0, 2, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 2,
       2, 2, 2, 0, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 1, 2, 1, 0, 1, 2, 2, 1,
       2, 0, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1, 0, 0, 0, 2, 1, 0, 0, 1, 1,
       0, 0, 2, 0, 2, 2, 1, 1, 1, 1, 1, 1, 0, 2, 1, 2, 1, 0, 0, 2, 0, 2,
       0, 2, 1, 0, 1, 2, 1, 2, 1, 1, 2, 1, 0, 2, 0, 2, 1, 1, 2, 0, 1, 0,
       2, 1, 2, 0, 0, 1, 0, 1, 0, 2, 1, 2, 1, 0, 1, 0, 2, 2, 1, 1, 2, 0,
       0, 1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 1, 1,
       1, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0,
       0, 2, 1, 2, 1, 1, 0, 1, 1, 0, 1, 1, 2, 0, 1, 2, 0, 0, 2, 1, 1, 2,
       2, 1, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 2, 1, 2, 1, 2, 2, 1, 0, 1, 1,
       2, 2, 2, 2, 0, 1, 0, 0, 1, 2, 0, 0, 0, 2])

In [14]:
from sklearn.decomposition import PCA
from sklearn.datasets import make_blobs
n_samples =20
random_state=20
X,y=make_blobs(n_samples=n_samples,n_features=10,random_state=None)
X.shape

(20, 10)

In [15]:
pca=PCA(n_components=3)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [16]:
pca.explained_variance_ratio_

array([0.69399618, 0.2811217 , 0.00621954])

In [17]:
first_pca = pca.components_[0]
first_pca

array([ 0.22815792,  0.19989226, -0.35242707, -0.53229185,  0.31260067,
        0.54831766,  0.20364924,  0.16792382, -0.09029722, -0.15572779])

In [18]:
pca_reduced=pca.transform(X)
pca_reduced.shape

(20, 3)

In [19]:
#pipeline 
from sklearn.pipeline import Pipeline
#import logistic regression estimator
from sklearn.linear_model import LinearRegression

In [20]:
#import linear estimator
from sklearn.linear_model import LinearRegression
#import PCA estimator for dimentionality reduction
from sklearn.decomposition import PCA

In [21]:
#Chain the estimators together
estimator=[('dim_reduction',PCA(),'linear_model',LinearRegression())]
#put the chain of estimator in the pipeline Object
pipeline_estimator = Pipeline(estimator)
#check the chain of estimators
pipeline_estimator

ValueError: too many values to unpack (expected 2)